name: lecteur_multimedia
description: "Lecteur multimedia audio et video"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: any
  video_player: any
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.22

flutter:
  uses-material-design: true
